apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: ghcr.io/arnaudpillac/otel-auto-instrumentation-test/python-hello:main
          ports:
            - containerPort: 5000
          resources: {}

